name: Release

on:
  workflow_dispatch: 
  pull_request:    
    branches:
      - main 

permissions:
  contents: read

jobs:
  release:
    permissions:
      actions: read
      id-token: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
      - name: Run release actions
        run: echo "Run release logic here"
